@echo off
setlocal

set "SCRIPT_DIR=%~dp0"
set "GEO_ENV_SHOW_SUMMARY=1"
if not defined NOISE_OGR2OGR_GDB_WORKERS set "NOISE_OGR2OGR_GDB_WORKERS=2"
if not defined NOISE_OGR2OGR_GDB_CHUNK_SIZE set "NOISE_OGR2OGR_GDB_CHUNK_SIZE=50"
if not defined NOISE_OGR2OGR_IDLE_TIMEOUT_SEC set "NOISE_OGR2OGR_IDLE_TIMEOUT_SEC=2400"
if not defined NOISE_OGR2OGR_ROAD_CHUNK_TIMEOUT_SEC set "NOISE_OGR2OGR_ROAD_CHUNK_TIMEOUT_SEC=3600"
if not defined NOISE_OGR2OGR_TOTAL_TIMEOUT_SEC set "NOISE_OGR2OGR_TOTAL_TIMEOUT_SEC=7200"
if not defined NOISE_OGR2OGR_TIMEOUT_SECONDS set "NOISE_OGR2OGR_TIMEOUT_SECONDS=900"
if not defined NOISE_OGR2OGR_HARD_TIMEOUT_SECONDS set "NOISE_OGR2OGR_HARD_TIMEOUT_SECONDS=900"
if not defined NOISE_OGR2OGR_NO_PROGRESS_TIMEOUT_SECONDS set "NOISE_OGR2OGR_NO_PROGRESS_TIMEOUT_SECONDS=180"
if not defined NOISE_PRECOMPUTE_WATCHDOG_TIMEOUT_SEC set "NOISE_PRECOMPUTE_WATCHDOG_TIMEOUT_SEC=1200"

powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT_DIR%run_noise_precompute_watchdog.ps1" -Incremental
exit /b %errorlevel%
